"""Move registry for the state-based tactical wrestling simulation.

Each move entry contains the required fields:
- damage: int
- cost: int (Grit)
- type: one of (Strike, Grapple, Aerial, Submission, Pin, Setup)
- req_user_state: one of (STANDING, GROUNDED, TOP_ROPE, RUNNING, GRAPPLED, ANY)
- req_target_state: one of (STANDING, GROUNDED, TOP_ROPE, RUNNING, GRAPPLED, ANY)
- flavor_text: str

N64 additions:
- target_part: one of (HEAD, BODY, LEGS, NONE)
- hype_gain: int (0-100). Applied only on successful execution.
- is_finisher: bool

Optional fields used by the engine:
- set_user_state: str
- set_target_state: str
- notes: str (non-functional metadata)
"""

from __future__ import annotations

from typing import Any, Dict


Move = Dict[str, Any]


MOVES: Dict[str, Move] = {
    # --- Universal / economy ---
    "Rest": {
        "damage": 0,
        "cost": 0,
        "type": "Setup",
        "req_user_state": "ANY",
        "req_target_state": "ANY",
        "target_part": "NONE",
        "hype_gain": 0,
        "is_finisher": False,
        "flavor_text": "You create space and breathe...",
        "notes": "High regen handled by engine.",
    },

    "Taunt": {
        "damage": 0,
        "cost": 0,
        "type": "Setup",
        "req_user_state": "STANDING",
        "req_target_state": "ANY",
        "target_part": "NONE",
        "hype_gain": 35,
        "is_finisher": False,
        "flavor_text": "You showboat to the crowd and fire up!",
        "notes": "Big hype gain; no damage.",
    },

    "Slow Stand Up": {
        "damage": 0,
        "cost": 0,
        "type": "Setup",
        "req_user_state": "GROUNDED",
        "req_target_state": "ANY",
        "target_part": "NONE",
        "hype_gain": 0,
        "is_finisher": False,
        "flavor_text": "They crawl toward the ropes and try to rise...",
        "set_user_state": "STANDING",
        "notes": "Engine applies a success chance; on failure you remain grounded.",
    },

    # --- Neutral (standing) gate: strikes + attempt grapple + taunt/rest ---
    "Lock Up": {
        "damage": 0,
        "cost": 2,
        "type": "Setup",
        "req_user_state": "STANDING",
        "req_target_state": "STANDING",
        "target_part": "NONE",
        "hype_gain": 2,
        "is_finisher": False,
        "flavor_text": "You step in and reach for a hold...",
        "notes": "Engine runs neutral RPS vs CPU intent; may trigger lock-up.",
    },

    # Legacy/internal alias (kept to avoid stray references; never legal)
    "Attempt Grapple": {
        "damage": 0,
        "cost": 0,
        "type": "Setup",
        "req_user_state": "HIDDEN",
        "req_target_state": "HIDDEN",
        "target_part": "NONE",
        "hype_gain": 0,
        "is_finisher": False,
        "flavor_text": "(internal)",
        "notes": "Deprecated alias: use Lock Up.",
    },
    "Jab": {
        "damage": 5,
        "cost": 2,
        "type": "Strike",
        "req_user_state": "STANDING",
        "req_target_state": "STANDING",
        "target_part": "HEAD",
        "hype_gain": 4,
        "is_finisher": False,
        "flavor_text": "A quick jab snaps their head back!",
    },
    "Desperation Slap": {
        "damage": 1,
        "cost": 0,
        "type": "Strike",
        "req_user_state": "STANDING",
        "req_target_state": "STANDING",
        "target_part": "HEAD",
        "hype_gain": 1,
        "is_finisher": False,
        "flavor_text": "A tired slap—more annoyance than impact.",
        "notes": "Intended as a 0-grit option; engine gives it a high evade chance.",
    },
    "Front Kick": {
        "damage": 7,
        "cost": 3,
        "type": "Strike",
        "req_user_state": "STANDING",
        "req_target_state": "STANDING",
        "target_part": "BODY",
        "hype_gain": 6,
        "is_finisher": False,
        "flavor_text": "A stiff kick to the midsection doubles them over!",
    },
    "Snap Suplex": {
        "damage": 11,
        "cost": 5,
        "type": "Grapple",
        "req_user_state": "GRAPPLED",
        "req_target_state": "GRAPPLED",
        "target_part": "BODY",
        "hype_gain": 12,
        "is_finisher": False,
        "flavor_text": "Hooks the waist and snaps them down!",
        "set_user_state": "STANDING",
        "set_target_state": "GROUNDED",
    },
    "DDT": {
        "damage": 14,
        "cost": 6,
        "type": "Grapple",
        "req_user_state": "GRAPPLED",
        "req_target_state": "GRAPPLED",
        "target_part": "HEAD",
        "hype_gain": 14,
        "is_finisher": True,
        "flavor_text": "Front facelock—DDT! Spiked to the canvas!",
        "set_user_state": "STANDING",
        "set_target_state": "GROUNDED",
    },
    "Powerbomb": {
        "damage": 20,
        "cost": 8,
        "type": "Grapple",
        "req_user_state": "GRAPPLED",
        "req_target_state": "GRAPPLED",
        "target_part": "BODY",
        "hype_gain": 18,
        "is_finisher": True,
        "flavor_text": "Hoists them up—POWERBOMB! The ring shakes!",
        "set_user_state": "STANDING",
        "set_target_state": "GROUNDED",
    },

    # --- State transitions / momentum ---
    "Irish Whip": {
        "damage": 0,
        "cost": 3,
        "type": "Grapple",
        "req_user_state": "GRAPPLED",
        "req_target_state": "GRAPPLED",
        "target_part": "LEGS",
        "hype_gain": 8,
        "is_finisher": False,
        "flavor_text": "Sends them to the ropes with an Irish Whip!",
        "set_user_state": "STANDING",
        "set_target_state": "RUNNING",
    },
    "Clothesline": {
        "damage": 10,
        "cost": 4,
        "type": "Strike",
        "req_user_state": "STANDING",
        "req_target_state": "RUNNING",
        "target_part": "HEAD",
        "hype_gain": 10,
        "is_finisher": False,
        "flavor_text": "CLOTHESLINE! They flip inside-out and crash to the mat!",
        "set_target_state": "GROUNDED",
    },

    "Back Body Drop": {
        "damage": 12,
        "cost": 4,
        "type": "Grapple",
        "req_user_state": "STANDING",
        "req_target_state": "RUNNING",
        "target_part": "BODY",
        "hype_gain": 12,
        "is_finisher": False,
        "flavor_text": "Catches them charging in—BACK BODY DROP!",
        "set_target_state": "GROUNDED",
    },
    "Climb Turnbuckle": {
        "damage": 0,
        "cost": 2,
        "type": "Setup",
        "req_user_state": "STANDING",
        "req_target_state": "ANY",
        "target_part": "NONE",
        "hype_gain": 2,
        "is_finisher": False,
        "flavor_text": "You scale the turnbuckles and steady your footing...",
        "set_user_state": "TOP_ROPE",
    },
    "Climb Down": {
        "damage": 0,
        "cost": 0,
        "type": "Setup",
        "req_user_state": "TOP_ROPE",
        "req_target_state": "ANY",
        "target_part": "NONE",
        "hype_gain": 0,
        "is_finisher": False,
        "flavor_text": "They climb back down to the mat.",
        "set_user_state": "STANDING",
        "notes": "Prevents TOP_ROPE soft-locks.",
    },
    "Shove Off Turnbuckle": {
        "damage": 8,
        "cost": 4,
        "type": "Strike",
        "req_user_state": "STANDING",
        "req_target_state": "TOP_ROPE",
        "target_part": "BODY",
        "hype_gain": 10,
        "is_finisher": False,
        "flavor_text": "A nasty shove sends them crashing down!",
        "set_target_state": "GROUNDED",
    },
    "Superplex": {
        "damage": 22,
        "cost": 10,
        "type": "Grapple",
        "req_user_state": "TOP_ROPE",
        "req_target_state": "TOP_ROPE",
        "target_part": "BODY",
        "hype_gain": 25,
        "is_finisher": True,
        "flavor_text": "Hooks them up top—SUPERPLEX! Both bodies hit hard!",
        "set_user_state": "GROUNDED",
        "set_target_state": "GROUNDED",
        "notes": "High risk/high reward; can break 'both top rope' stalls.",
    },
    "Kip-up": {
        "damage": 0,
        "cost": 2,
        "type": "Setup",
        "req_user_state": "GROUNDED",
        "req_target_state": "ANY",
        "target_part": "NONE",
        "hype_gain": 4,
        "is_finisher": False,
        "flavor_text": "You spring to your feet with a kip-up!",
        "set_user_state": "STANDING",
    },
    "Possum": {
        "damage": 0,
        "cost": 3,
        "type": "Setup",
        "req_user_state": "GROUNDED",
        "req_target_state": "STANDING",
        "target_part": "NONE",
        "hype_gain": 5,
        "is_finisher": False,
        "flavor_text": "You play possum... then explode with a cheap roll-up threat!",
        "set_user_state": "STANDING",
        "notes": "Engine applies a small chance to trip the opponent grounded.",
    },

    # --- If you get whipped / forced into motion ---
    "Stop Short": {
        "damage": 0,
        "cost": 1,
        "type": "Setup",
        "req_user_state": "RUNNING",
        "req_target_state": "ANY",
        "target_part": "NONE",
        "hype_gain": 0,
        "is_finisher": False,
        "flavor_text": "You put on the brakes and reset your stance!",
        "set_user_state": "STANDING",
    },
    "Rebound Lariat": {
        "damage": 9,
        "cost": 4,
        "type": "Strike",
        "req_user_state": "RUNNING",
        "req_target_state": "STANDING",
        "target_part": "HEAD",
        "hype_gain": 12,
        "is_finisher": False,
        "flavor_text": "Off the ropes—REBOUND LARIAT!",
        "set_user_state": "STANDING",
        "set_target_state": "GROUNDED",
    },

    # --- Grounded offense / finish attempts ---
    "Stomp": {
        "damage": 6,
        "cost": 2,
        "type": "Strike",
        "req_user_state": "STANDING",
        "req_target_state": "GROUNDED",
        "target_part": "BODY",
        "hype_gain": 4,
        "is_finisher": False,
        "flavor_text": "Boots down—no mercy!",
    },
    "Pick Up": {
        "damage": 0,
        "cost": 1,
        "type": "Setup",
        "req_user_state": "STANDING",
        "req_target_state": "GROUNDED",
        "target_part": "NONE",
        "hype_gain": 0,
        "is_finisher": False,
        "flavor_text": "You haul them back up to their feet.",
        "set_target_state": "STANDING",
    },
    "Pin": {
        "damage": 0,
        "cost": 3,
        "type": "Pin",
        "req_user_state": "STANDING",
        "req_target_state": "GROUNDED",
        "target_part": "NONE",
        "hype_gain": 6,
        "is_finisher": False,
        "flavor_text": "Hooks the leg! Going for the cover!",
    },
    "Submission Hold": {
        "damage": 0,
        "cost": 4,
        "type": "Submission",
        "req_user_state": "STANDING",
        "req_target_state": "GROUNDED",
        "target_part": "BODY",
        "hype_gain": 8,
        "is_finisher": True,
        "flavor_text": "You cinch it in deep—nowhere to go!",
    },

    # --- In-grapple mini-game ---
    "Chain Wrestle": {
        "damage": 0,
        "cost": 0,
        "type": "Setup",
        "req_user_state": "GRAPPLED",
        "req_target_state": "GRAPPLED",
        "target_part": "NONE",
        "hype_gain": 5,
        "is_finisher": False,
        "flavor_text": "You shift your weight and fight for control...",
        "notes": "Engine runs blind RPS (POWER/SPEED/TECHNICAL).",
    },

    # --- Top rope offense ---
    "Moonsault": {
        "damage": 16,
        "cost": 7,
        "type": "Aerial",
        "req_user_state": "TOP_ROPE",
        "req_target_state": "GROUNDED",
        "target_part": "BODY",
        "hype_gain": 22,
        "is_finisher": True,
        "flavor_text": "MOONSAULT! Picture-perfect rotation!",
        "set_user_state": "STANDING",
    },
    "Diving Elbow": {
        "damage": 13,
        "cost": 6,
        "type": "Aerial",
        "req_user_state": "TOP_ROPE",
        "req_target_state": "GROUNDED",
        "target_part": "BODY",
        "hype_gain": 18,
        "is_finisher": False,
        "flavor_text": "You soar through the air—DIVING ELBOW!",
        "set_user_state": "STANDING",
    },
}
