"""Move registry for the state-based tactical wrestling simulation.

Refactored for AKI-style Hierarchy:
STANDING -> GRAPPLE_WEAK -> GRAPPLE_STRONG -> GRAPPLE_BACK

NOTE: Keys are stable slugs (IDs). Use move["name"] for display.
"""
from __future__ import annotations

from collections import OrderedDict
from typing import Any, Dict

Move = Dict[str, Any]

MOVES: Dict[str, Move] = {'def_defensive': OrderedDict([('name', 'Defensive'),
                               ('damage', 0),
                               ('cost', 0),
                               ('type', 'Defensive'),
                               ('req_user_state', 'ANY'),
                               ('req_target_state', 'ANY'),
                               ('target_part', 'NONE'),
                               ('hype_gain', 0),
                               ('is_finisher', False),
                               ('flavor_text', 'You brace, slip away, and buy yourself a beat...'),
                               ('notes',
                                'Phase 2: Special resolution. Discard up to 2 cards (<=5). Can never win a clash; used '
                                'to survive pressure.')]),
 'util_rest': OrderedDict([('name', 'Rest'),
                           ('damage', 0),
                           ('cost', 0),
                           ('type', 'Setup'),
                           ('req_user_state', 'ANY'),
                           ('req_target_state', 'ANY'),
                           ('target_part', 'NONE'),
                           ('hype_gain', 0),
                           ('is_finisher', False),
                           ('flavor_text', 'You create space and breathe...'),
                           ('notes', 'High regen handled by engine.')]),
 'util_groggy_recovery': OrderedDict([('name', 'Groggy Recovery'),
                                      ('damage', 0),
                                      ('cost', 0),
                                      ('type', 'Setup'),
                                      ('req_user_state', 'ANY'),
                                      ('req_target_state', 'ANY'),
                                      ('target_part', 'NONE'),
                                      ('hype_gain', 0),
                                      ('is_finisher', False),
                                      ('clash_mod', -4),
                                      ('flavor_text', 'You shake off the cobwebs...'),
                                      ('notes',
                                       'Only available while groggy. Weak/capped card play (max card value 7).')]),
 'util_taunt': OrderedDict([('name', 'Taunt'),
                            ('damage', 0),
                            ('cost', 0),
                            ('type', 'Setup'),
                            ('req_user_state', 'STANDING'),
                            ('req_target_state', 'ANY'),
                            ('target_part', 'NONE'),
                            ('hype_gain', 35),
                            ('is_finisher', False),
                            ('flavor_text', 'You showboat to the crowd and fire up!')]),
 'util_slow_stand_up': OrderedDict([('name', 'Slow Stand Up'),
                                    ('damage', 0),
                                    ('cost', 0),
                                    ('type', 'Setup'),
                                    ('req_user_state', 'GROUNDED'),
                                    ('req_target_state', 'ANY'),
                                    ('target_part', 'NONE'),
                                    ('hype_gain', 0),
                                    ('is_finisher', False),
                                    ('flavor_text', 'They crawl toward the ropes and try to rise...'),
                                    ('set_user_state', 'STANDING')]),
 'util_kip_up': OrderedDict([('name', 'Kip-up'),
                             ('damage', 0),
                             ('cost', 2),
                             ('type', 'Setup'),
                             ('req_user_state', 'GROUNDED'),
                             ('req_target_state', 'ANY'),
                             ('target_part', 'NONE'),
                             ('hype_gain', 4),
                             ('is_finisher', False),
                             ('flavor_text', 'You spring to your feet with a kip-up!'),
                             ('set_user_state', 'STANDING')]),
 'grap_lock_up': OrderedDict([('name', 'Lock Up'),
                              ('damage', 0),
                              ('ai_score', 10),
                              ('cost', 2),
                              ('type', 'Setup'),
                              ('req_user_state', 'STANDING'),
                              ('req_target_state', 'STANDING'),
                              ('set_user_state', 'GRAPPLE_WEAK'),
                              ('set_target_state', 'GRAPPLE_WEAK'),
                              ('target_part', 'NONE'),
                              ('hype_gain', 2),
                              ('is_finisher', False),
                              ('flavor_text', 'You step in and tie up with them!'),
                              ('notes', 'Engine runs neutral RPS; triggers entry to WEAK state.')]),
 'strike_jab': OrderedDict([('name', 'Jab'),
                            ('damage', 5),
                            ('cost', 2),
                            ('type', 'Strike'),
                            ('req_user_state', 'STANDING'),
                            ('req_target_state', 'STANDING'),
                            ('target_part', 'HEAD'),
                            ('hype_gain', 4),
                            ('is_finisher', False),
                            ('flavor_text', 'A quick jab snaps their head back!')]),
 'strike_chop': OrderedDict([('name', 'Chop'),
                             ('damage', 3),
                             ('cost', 0),
                             ('type', 'Strike'),
                             ('req_user_state', 'STANDING'),
                             ('req_target_state', 'STANDING'),
                             ('target_part', 'BODY'),
                             ('hype_gain', 2),
                             ('is_finisher', False),
                             ('flavor_text', 'A loud chop echoes through the arena!')]),
 'strike_front_kick': OrderedDict([('name', 'Front Kick'),
                                   ('damage', 7),
                                   ('cost', 3),
                                   ('type', 'Strike'),
                                   ('req_user_state', 'STANDING'),
                                   ('req_target_state', 'STANDING'),
                                   ('target_part', 'BODY'),
                                   ('hype_gain', 6),
                                   ('is_finisher', False),
                                   ('flavor_text', 'A stiff kick to the midsection doubles them over!')]),
 'strike_desperation_slap': OrderedDict([('name', 'Desperation Slap'),
                                         ('damage', 1),
                                         ('cost', 0),
                                         ('type', 'Strike'),
                                         ('req_user_state', 'STANDING'),
                                         ('req_target_state', 'STANDING'),
                                         ('target_part', 'HEAD'),
                                         ('hype_gain', 1),
                                         ('is_finisher', False),
                                         ('flavor_text', 'A tired slap—more annoyance than impact.')]),
 'util_deepen_hold': OrderedDict([('name', 'Deepen Hold'),
                                  ('damage', 0),
                                  ('ai_score', 8),
                                  ('cost', 0),
                                  ('type', 'Setup'),
                                  ('req_user_state', 'GRAPPLE_WEAK'),
                                  ('req_target_state', 'GRAPPLE_WEAK'),
                                  ('set_user_state', 'GRAPPLE_STRONG'),
                                  ('set_target_state', 'GRAPPLE_STRONG'),
                                  ('target_part', 'NONE'),
                                  ('hype_gain', 0),
                                  ('is_finisher', False),
                                  ('flavor_text', 'You shift your weight to secure a deeper hold...'),
                                  ('notes', 'Triggers chain wrestling minigame.')]),
 'grap_go_behind': OrderedDict([('name', 'Go Behind'),
                                ('damage', 0),
                                ('ai_score', 12),
                                ('cost', 0),
                                ('type', 'Grapple'),
                                ('req_user_state', 'GRAPPLE_STRONG'),
                                ('req_target_state', 'GRAPPLE_ANY'),
                                ('set_user_state', 'GRAPPLE_BACK'),
                                ('set_target_state', 'GRAPPLE_BACK'),
                                ('target_part', 'NONE'),
                                ('hype_gain', 5),
                                ('is_finisher', False),
                                ('flavor_text', 'You duck under the arm and secure the waistlock!')]),
 'grap_irish_whip': OrderedDict([('name', 'Irish Whip'),
                                 ('damage', 0),
                                 ('ai_score', 10),
                                 ('cost', 3),
                                 ('type', 'Grapple'),
                                 ('req_user_state', 'GRAPPLE_WEAK'),
                                 ('req_target_state', 'GRAPPLE_WEAK'),
                                 ('set_user_state', 'STANDING'),
                                 ('set_target_state', 'TOSSED'),
                                 ('target_part', 'LEGS'),
                                 ('hype_gain', 5),
                                 ('is_finisher', False),
                                 ('flavor_text', 'Sends them to the ropes with an Irish Whip!')]),
 'grap_snap_suplex': OrderedDict([('name', 'Snap Suplex'),
                                  ('damage', 11),
                                  ('cost', 5),
                                  ('type', 'Grapple'),
                                  ('req_user_state', 'GRAPPLE_WEAK'),
                                  ('req_target_state', 'GRAPPLE_WEAK'),
                                  ('ai_score', 8),
                                  ('set_user_state', 'STANDING'),
                                  ('set_target_state', 'GROUNDED'),
                                  ('target_part', 'BODY'),
                                  ('hype_gain', 10),
                                  ('is_finisher', False),
                                  ('flavor_text', 'Hooks the waist and snaps them down!')]),
 'grap_arm_drag': OrderedDict([('name', 'Arm Drag'),
                               ('damage', 8),
                               ('cost', 3),
                               ('type', 'Grapple'),
                               ('req_user_state', 'GRAPPLE_WEAK'),
                               ('req_target_state', 'GRAPPLE_WEAK'),
                               ('set_user_state', 'STANDING'),
                               ('set_target_state', 'GROUNDED'),
                               ('target_part', 'BODY'),
                               ('hype_gain', 6),
                               ('is_finisher', False),
                               ('flavor_text', 'Fluid motion—over they go with an arm drag!')]),
 'strike_forearm_club': OrderedDict([('name', 'Forearm Club'),
                                     ('damage', 6),
                                     ('cost', 0),
                                     ('type', 'Strike'),
                                     ('req_user_state', 'GRAPPLE_WEAK'),
                                     ('req_target_state', 'GRAPPLE_ANY'),
                                     ('target_part', 'HEAD'),
                                     ('hype_gain', 4),
                                     ('is_finisher', False),
                                     ('flavor_text', 'You smash a forearm into their neck!')]),
 'strike_knee_to_gut': OrderedDict([('name', 'Knee to Gut'),
                                    ('damage', 8),
                                    ('cost', 1),
                                    ('type', 'Strike'),
                                    ('req_user_state', 'GRAPPLE_WEAK'),
                                    ('req_target_state', 'GRAPPLE_ANY'),
                                    ('target_part', 'BODY'),
                                    ('hype_gain', 6),
                                    ('is_finisher', False),
                                    ('flavor_text', 'You drive a hard knee into the midsection.')]),
 'strike_gut_punch': OrderedDict([('name', 'Gut Punch'),
                                  ('damage', 2),
                                  ('ai_score', 4),
                                  ('cost', 0),
                                  ('type', 'Strike'),
                                  ('req_user_state', 'GRAPPLE_ANY'),
                                  ('req_target_state', 'GRAPPLE_ANY'),
                                  ('target_part', 'BODY'),
                                  ('hype_gain', 2),
                                  ('is_finisher', False),
                                  ('flavor_text', 'Short strike to the gut to create space!')]),
 'strike_ear_clap': OrderedDict([('name', 'Ear Clap'),
                                 ('damage', 4),
                                 ('cost', 0),
                                 ('type', 'Strike'),
                                 ('req_user_state', 'GRAPPLE_DEFENSE'),
                                 ('req_target_state', 'GRAPPLE_ANY'),
                                 ('target_part', 'HEAD'),
                                 ('hype_gain', 4),
                                 ('is_finisher', False),
                                 ('flavor_text', 'You box their ears to disorient them!')]),
 'grap_throw_to_corner': OrderedDict([('name', 'Throw to Corner'),
                                      ('damage', 0),
                                      ('ai_score', 12),
                                      ('cost', 0),
                                      ('type', 'Grapple'),
                                      ('req_user_state', 'GRAPPLE_WEAK'),
                                      ('req_target_state', 'GRAPPLE_WEAK'),
                                      ('set_user_state', 'STANDING'),
                                      ('set_target_state', 'CORNERED'),
                                      ('target_part', 'NONE'),
                                      ('hype_gain', 4),
                                      ('is_finisher', False),
                                      ('chain_next', 'grap_lift_to_turnbuckle'),
                                      ('chain_bonus', 4),
                                      ('flavor_text', 'You hurl them into the corner!')]),
 'strike_upkick': OrderedDict([('name', 'Upkick'),
                               ('damage', 6),
                               ('ai_score', 8),
                               ('cost', 0),
                               ('type', 'Strike'),
                               ('req_user_state', 'GROUNDED'),
                               ('req_target_state', 'STANDING'),
                               ('target_part', 'LEGS'),
                               ('hype_gain', 3),
                               ('is_finisher', False),
                               ('flavor_text', 'A snap kick from the back to drive them away!'),
                               ('notes', 'Grounded counter: gives the downed wrestler a way to fight back.')]),
 'grap_lift_to_turnbuckle': OrderedDict([('name', 'Lift to Turnbuckle'),
                                         ('damage', 0),
                                         ('cost', 0),
                                         ('type', 'Grapple'),
                                         ('req_user_state', 'STANDING'),
                                         ('req_target_state', 'CORNERED'),
                                         ('set_user_state', 'TOP_ROPE'),
                                         ('set_target_state', 'TOP_ROPE'),
                                         ('target_part', 'NONE'),
                                         ('hype_gain', 6),
                                         ('is_finisher', False),
                                         ('chain_next', 'grap_superplex'),
                                         ('chain_bonus', 4),
                                         ('flavor_text',
                                          'You lift them up to the turnbuckle—both are headed up top!')]),
 'grap_weak_knee': OrderedDict([('name', 'Weak Knee'),
                                ('damage', 3),
                                ('cost', 0),
                                ('type', 'Grapple'),
                                ('req_user_state', 'GRAPPLE_ANY'),
                                ('req_target_state', 'GRAPPLE_ANY'),
                                ('target_part', 'LEGS'),
                                ('hype_gain', 1),
                                ('is_finisher', False),
                                ('flavor_text', 'A quick knee to the thigh to slow them down.'),
                                ('notes', 'Cheap in-grapple option (0 grit).')]),
 'grap_headbutt': OrderedDict([('name', 'Headbutt'),
                               ('damage', 5),
                               ('cost', 0),
                               ('type', 'Grapple'),
                               ('req_user_state', 'GRAPPLE_WEAK'),
                               ('req_target_state', 'GRAPPLE_ANY'),
                               ('target_part', 'HEAD'),
                               ('hype_gain', 5),
                               ('is_finisher', False),
                               ('flavor_text', 'A quick, nasty strike from the clinch.')]),
 'grap_knee_strike': OrderedDict([('name', 'Knee Strike'),
                                  ('damage', 8),
                                  ('cost', 2),
                                  ('type', 'Grapple'),
                                  ('req_user_state', 'GRAPPLE_WEAK'),
                                  ('req_target_state', 'GRAPPLE_ANY'),
                                  ('target_part', 'BODY'),
                                  ('hype_gain', 8),
                                  ('is_finisher', False),
                                  ('flavor_text', 'You pull their head down into a rising knee!')]),
 'strike_desperation_punch': OrderedDict([('name', 'Desperation Punch'),
                                          ('damage', 4),
                                          ('cost', 0),
                                          ('type', 'Strike'),
                                          ('req_user_state', 'GRAPPLE_DEFENSE'),
                                          ('req_target_state', 'GRAPPLE_ANY'),
                                          ('target_part', 'HEAD'),
                                          ('hype_gain', 5),
                                          ('is_finisher', False),
                                          ('flavor_text', 'You fire a wild punch to create separation!')]),
 'strike_bite': OrderedDict([('name', 'Bite'),
                             ('damage', 8),
                             ('cost', 5),
                             ('type', 'Strike'),
                             ('req_user_state', 'GRAPPLE_DEFENSE'),
                             ('req_target_state', 'GRAPPLE_ANY'),
                             ('target_part', 'HEAD'),
                             ('hype_gain', 15),
                             ('is_finisher', False),
                             ('flavor_text', 'You sink your teeth in! Dirty but effective!')]),
 'grap_fight_for_control': OrderedDict([('name', 'Fight For Control'),
                                        ('damage', 0),
                                        ('ai_score', 9),
                                        ('cost', 0),
                                        ('type', 'Setup'),
                                        ('req_user_state', 'GRAPPLE_ANY'),
                                        ('req_target_state', 'GRAPPLE_ANY'),
                                        ('target_part', 'NONE'),
                                        ('hype_gain', 5),
                                        ('is_finisher', False),
                                        ('flavor_text', 'You fight for better positioning...'),
                                        ('notes', 'Phase 2: used to contest control inside grapples.')]),
 'grap_shove_off': OrderedDict([('name', 'Shove Off'),
                                ('damage', 0),
                                ('ai_score', 6),
                                ('cost', 1),
                                ('type', 'Setup'),
                                ('req_user_state', 'ANY'),
                                ('req_target_state', 'GRAPPLE_ANY'),
                                ('target_part', 'NONE'),
                                ('hype_gain', 1),
                                ('is_finisher', False),
                                ('flavor_text', 'You shove off and try to reset the scramble!'),
                                ('notes', 'Breaks the grapple and resets both to STANDING.')]),
 'grap_ddt': OrderedDict([('name', 'DDT'),
                          ('damage', 16),
                          ('cost', 6),
                          ('type', 'Grapple'),
                          ('req_user_state', 'GRAPPLE_STRONG'),
                          ('req_target_state', 'GRAPPLE_STRONG'),
                          ('ai_score', 12),
                          ('set_user_state', 'STANDING'),
                          ('set_target_state', 'GROUNDED'),
                          ('target_part', 'HEAD'),
                          ('hype_gain', 15),
                          ('is_finisher', True),
                          ('flavor_text', 'Front facelock... DDT! Spiked to the canvas!')]),
 'grap_powerbomb': OrderedDict([('name', 'Powerbomb'),
                                ('damage', 22),
                                ('cost', 8),
                                ('type', 'Grapple'),
                                ('req_user_state', 'GRAPPLE_STRONG'),
                                ('req_target_state', 'GRAPPLE_STRONG'),
                                ('ai_score', 10),
                                ('set_user_state', 'STANDING'),
                                ('set_target_state', 'GROUNDED'),
                                ('target_part', 'BODY'),
                                ('hype_gain', 20),
                                ('is_finisher', True),
                                ('flavor_text', 'Hoists them up... POWERBOMB! The ring shakes!')]),
 'grap_piledriver': OrderedDict([('name', 'Piledriver'),
                                 ('damage', 20),
                                 ('cost', 7),
                                 ('type', 'Grapple'),
                                 ('req_user_state', 'GRAPPLE_STRONG'),
                                 ('req_target_state', 'GRAPPLE_STRONG'),
                                 ('set_user_state', 'STANDING'),
                                 ('set_target_state', 'GROUNDED'),
                                 ('target_part', 'HEAD'),
                                 ('hype_gain', 18),
                                 ('is_finisher', False),
                                 ('flavor_text', 'Head between the legs... PILEDRIVER! That neck is compressed!')]),
 'sub_bearhug': OrderedDict([('name', 'Bearhug'),
                             ('damage', 12),
                             ('cost', 5),
                             ('type', 'Submission'),
                             ('req_user_state', 'GRAPPLE_STRONG'),
                             ('req_target_state', 'GRAPPLE_STRONG'),
                             ('ai_score', 9),
                             ('set_target_state', 'GRAPPLE_STRONG'),
                             ('target_part', 'BODY'),
                             ('hype_gain', 10),
                             ('is_finisher', False),
                             ('flavor_text', 'Squeezing the life out of them with a Bearhug!'),
                             ('notes', 'Does not break the hold; stays in Strong state.')]),
 'grap_german_suplex': OrderedDict([('name', 'German Suplex'),
                                    ('damage', 18),
                                    ('cost', 7),
                                    ('type', 'Grapple'),
                                    ('req_user_state', 'GRAPPLE_BACK'),
                                    ('req_target_state', 'GRAPPLE_BACK'),
                                    ('ai_score', 6),
                                    ('set_user_state', 'STANDING'),
                                    ('set_target_state', 'GROUNDED'),
                                    ('target_part', 'HEAD'),
                                    ('hype_gain', 16),
                                    ('is_finisher', True),
                                    ('flavor_text', 'Waistlock from behind... GERMAN SUPLEX! High angle bridge!')]),
 'grap_backbreaker': OrderedDict([('name', 'Backbreaker'),
                                  ('damage', 14),
                                  ('cost', 5),
                                  ('type', 'Grapple'),
                                  ('req_user_state', 'GRAPPLE_BACK'),
                                  ('req_target_state', 'GRAPPLE_BACK'),
                                  ('ai_score', 6),
                                  ('set_user_state', 'STANDING'),
                                  ('set_target_state', 'GROUNDED'),
                                  ('target_part', 'BODY'),
                                  ('hype_gain', 12),
                                  ('is_finisher', False),
                                  ('flavor_text', 'Lifts them up... and drops them knee-first on the spine!')]),
 'pin_schoolboy_pin': OrderedDict([('name', 'Schoolboy Pin'),
                                   ('damage', 0),
                                   ('cost', 4),
                                   ('type', 'Pin'),
                                   ('req_user_state', 'GRAPPLE_BACK'),
                                   ('req_target_state', 'GRAPPLE_BACK'),
                                   ('target_part', 'NONE'),
                                   ('hype_gain', 10),
                                   ('is_finisher', False),
                                   ('flavor_text', 'Quickly rolls them up for a Schoolboy Pin!')]),
 'strike_clothesline': OrderedDict([('name', 'Clothesline'),
                                    ('damage', 10),
                                    ('cost', 4),
                                    ('type', 'Strike'),
                                    ('req_user_state', 'STANDING'),
                                    ('req_target_state', 'TOSSED'),
                                    ('ai_score', 6),
                                    ('target_part', 'HEAD'),
                                    ('hype_gain', 10),
                                    ('is_finisher', False),
                                    ('flavor_text', 'CLOTHESLINE! They flip inside-out!')]),
 'grap_back_body_drop': OrderedDict([('name', 'Back Body Drop'),
                                     ('damage', 12),
                                     ('cost', 4),
                                     ('type', 'Grapple'),
                                     ('req_user_state', 'STANDING'),
                                     ('req_target_state', 'TOSSED'),
                                     ('ai_score', 10),
                                     ('target_part', 'BODY'),
                                     ('hype_gain', 12),
                                     ('is_finisher', False),
                                     ('flavor_text', 'Catches them charging in... BACK BODY DROP!')]),

 'util_charge': OrderedDict([('name', 'Charge'),
                             ('damage', 0),
                             ('ai_score', 5),
                             ('cost', 0),
                             ('type', 'Setup'),
                             ('req_user_state', 'STANDING'),
                             ('req_target_state', 'ANY'),
                             ('set_user_state', 'RUNNING'),
                             ('target_part', 'NONE'),
                             ('hype_gain', 2),
                             ('is_finisher', False),
                             ('flavor_text', 'You build speed—charging in!')]),

 'strike_running_clothesline': OrderedDict([('name', 'Running Clothesline'),
                                            ('damage', 12),
                                            ('cost', 3),
                                            ('type', 'Strike'),
                                            ('req_user_state', 'RUNNING'),
                                            ('req_target_state', 'STANDING'),
                                            ('ai_score', 6),
                                            ('set_user_state', 'STANDING'),
                                            ('set_target_state', 'GROUNDED'),
                                            ('target_part', 'HEAD'),
                                            ('hype_gain', 12),
                                            ('is_finisher', False),
                                            ('flavor_text', 'Full sprint—RUNNING CLOTHESLINE!')]),

 'strike_trip': OrderedDict([('name', 'Trip'),
                             ('damage', 6),
                             ('ai_score', 4),
                             ('cost', 0),
                             ('type', 'Strike'),
                             ('req_user_state', 'STANDING'),
                             ('req_target_state', 'TOSSED'),
                             ('set_target_state', 'GROUNDED'),
                             ('target_part', 'LEGS'),
                             ('hype_gain', 6),
                             ('is_finisher', False),
                             ('flavor_text', 'Sweeps the leg—down they go!')]),

 'util_regain_balance': OrderedDict([('name', 'Regain Balance'),
                                     ('damage', 0),
                                     ('ai_score', 5),
                                     ('cost', 0),
                                     ('type', 'Setup'),
                                     ('req_user_state', 'TOSSED'),
                                     ('req_target_state', 'ANY'),
                                     ('set_user_state', 'STANDING'),
                                     ('target_part', 'NONE'),
                                     ('hype_gain', 0),
                                     ('is_finisher', False),
                                     ('flavor_text', 'You grab the ropes and steady yourself!')]),
 'util_stop_short': OrderedDict([('name', 'Stop Short'),
                                 ('damage', 0),
                                 ('ai_score', 6),
                                 ('cost', 1),
                                 ('type', 'Setup'),
                                 ('req_user_state', 'RUNNING'),
                                 ('req_target_state', 'ANY'),
                                 ('set_user_state', 'STANDING'),
                                 ('target_part', 'NONE'),
                                 ('hype_gain', 0),
                                 ('is_finisher', False),
                                 ('flavor_text', 'You put on the brakes and reset your stance!')]),
 'strike_rebound_lariat': OrderedDict([('name', 'Rebound Lariat'),
                                       ('damage', 9),
                                       ('cost', 4),
                                       ('type', 'Strike'),
                                       ('req_user_state', 'RUNNING'),
                                       ('req_target_state', 'STANDING'),
                                       ('ai_score', 4),
                                       ('set_target_state', 'GROUNDED'),
                                       ('target_part', 'HEAD'),
                                       ('hype_gain', 12),
                                       ('is_finisher', False),
                                       ('flavor_text', 'Off the ropes... REBOUND LARIAT!')]),
 'strike_stomp': OrderedDict([('name', 'Stomp'),
                              ('damage', 6),
                              ('cost', 2),
                              ('type', 'Strike'),
                              ('req_user_state', 'STANDING'),
                              ('req_target_state', 'GROUNDED'),
                              ('target_part', 'BODY'),
                              ('hype_gain', 4),
                              ('is_finisher', False),
                              ('flavor_text', 'Boots down—no mercy!')]),
 'util_pick_up': OrderedDict([('name', 'Pick Up'),
                              ('damage', 0),
                              ('ai_score', 6),
                              ('cost', 1),
                              ('type', 'Setup'),
                              ('req_user_state', 'STANDING'),
                              ('req_target_state', 'GROUNDED'),
                              ('set_target_state', 'STANDING'),
                              ('target_part', 'NONE'),
                              ('hype_gain', 0),
                              ('is_finisher', False),
                              ('flavor_text', 'You haul them back up to their feet.')]),
 'pin_pin': OrderedDict([('name', 'Pin'),
                         ('damage', 0),
                         ('cost', 0),
                         ('type', 'Pin'),
                         ('req_user_state', 'STANDING'),
                         ('req_target_state', 'GROUNDED'),
                         ('target_part', 'NONE'),
                         ('hype_gain', 6),
                         ('is_finisher', False),
                         ('flavor_text', 'Hooks the leg! Going for the cover!')]),
 'sub_submission_hold': OrderedDict([('name', 'Submission Hold'),
                                     ('damage', 0),
                                     ('cost', 0),
                                     ('type', 'Submission'),
                                     ('req_user_state', 'STANDING'),
                                     ('req_target_state', 'GROUNDED'),
                                     ('target_part', 'BODY'),
                                     ('hype_gain', 8),
                                     ('is_finisher', True),
                                     ('flavor_text', 'You cinch it in deep—nowhere to go!')]),
 'util_possum': OrderedDict([('name', 'Possum'),
                             ('damage', 0),
                             ('cost', 3),
                             ('type', 'Setup'),
                             ('req_user_state', 'GROUNDED'),
                             ('req_target_state', 'STANDING'),
                             ('set_user_state', 'STANDING'),
                             ('target_part', 'NONE'),
                             ('hype_gain', 5),
                             ('is_finisher', False),
                             ('flavor_text', 'You play possum... then explode with a cheap roll-up threat!')]),
 'air_climb_turnbuckle': OrderedDict([('name', 'Climb Turnbuckle'),
                                      ('damage', 0),
                                      ('ai_score', 10),
                                      ('cost', 2),
                                      ('type', 'Setup'),
                                      ('req_user_state', 'STANDING'),
                                      ('req_target_state', 'ANY'),
                                      ('set_user_state', 'TOP_ROPE'),
                                      ('target_part', 'NONE'),
                                      ('hype_gain', 2),
                                      ('is_finisher', False),
                                      ('flavor_text', 'You scale the turnbuckles and steady your footing...')]),
 'air_climb_down': OrderedDict([('name', 'Climb Down'),
                                ('damage', 0),
                                ('ai_score', 4),
                                ('cost', 0),
                                ('type', 'Setup'),
                                ('req_user_state', 'TOP_ROPE'),
                                ('req_target_state', 'ANY'),
                                ('set_user_state', 'STANDING'),
                                ('target_part', 'NONE'),
                                ('hype_gain', 0),
                                ('is_finisher', False),
                                ('flavor_text', 'They climb back down to the mat.')]),
 'strike_shove_off_turnbuckle': OrderedDict([('name', 'Shove Off Turnbuckle'),
                                             ('damage', 8),
                                             ('cost', 4),
                                             ('type', 'Strike'),
                                             ('req_user_state', 'STANDING'),
                                             ('req_target_state', 'TOP_ROPE'),
                                             ('set_target_state', 'GROUNDED'),
                                             ('target_part', 'BODY'),
                                             ('hype_gain', 10),
                                             ('is_finisher', False),
                                             ('flavor_text', 'A nasty shove sends them crashing down!')]),
 'grap_superplex': OrderedDict([('name', 'Superplex'),
                                ('damage', 22),
                                ('cost', 10),
                                ('type', 'Grapple'),
                                ('req_user_state', 'TOP_ROPE'),
                                ('req_target_state', 'TOP_ROPE'),
                                ('set_user_state', 'GROUNDED'),
                                ('set_target_state', 'GROUNDED'),
                                ('target_part', 'BODY'),
                                ('hype_gain', 25),
                                ('is_finisher', True),
                                ('flavor_text', 'Hooks them up top—SUPERPLEX! Both bodies hit hard!')]),
 'air_moonsault': OrderedDict([('name', 'Moonsault'),
                               ('damage', 16),
                               ('cost', 7),
                               ('type', 'Aerial'),
                               ('req_user_state', 'TOP_ROPE'),
                               ('req_target_state', 'GROUNDED'),
                               ('set_user_state', 'STANDING'),
                               ('target_part', 'BODY'),
                               ('hype_gain', 22),
                               ('is_finisher', True),
                               ('flavor_text', 'MOONSAULT! Picture-perfect rotation!')]),
 'air_frog_splash': OrderedDict([('name', 'Frog Splash'),
                                 ('damage', 15),
                                 ('cost', 6),
                                 ('type', 'Aerial'),
                                 ('req_user_state', 'TOP_ROPE'),
                                 ('req_target_state', 'GROUNDED'),
                                 ('set_user_state', 'GROUNDED'),
                                 ('set_target_state', 'GROUNDED'),
                                 ('target_part', 'BODY'),
                                 ('hype_gain', 18),
                                 ('is_finisher', False),
                                 ('flavor_text', 'FROG SPLASH! All the weight across the ribs!')]),
 'air_diving_elbow': OrderedDict([('name', 'Diving Elbow'),
                                  ('damage', 13),
                                  ('cost', 6),
                                  ('type', 'Aerial'),
                                  ('req_user_state', 'TOP_ROPE'),
                                  ('req_target_state', 'GROUNDED'),
                                  ('set_user_state', 'STANDING'),
                                  ('target_part', 'BODY'),
                                  ('hype_gain', 18),
                                  ('is_finisher', False),
                                  ('flavor_text', 'You soar through the air—DIVING ELBOW!')])}


def _slug_to_display(slug: str) -> str:
    mv = MOVES.get(str(slug), {})
    return str(mv.get("name", slug))


# Backwards-compatible mapping for older code that still keys by display name.
# Do not mutate MOVES in-place; this is a derived view.
MOVES_BY_NAME: Dict[str, Move] = {}
for _slug, _mv in MOVES.items():
    _name = str(_mv.get("name", _slug))
    _copy = dict(_mv)
    for _k in ("chain_next", "chain_if_fail"):
        if _k in _copy and _copy[_k]:
            _copy[_k] = _slug_to_display(str(_copy[_k]))
    MOVES_BY_NAME[_name] = _copy
