"""Roster and AI profile data.

This is intentionally separated from the UI/game engine so the roster can grow
without bloating Main_kivy.py.
"""

from __future__ import annotations

# NOTE: Profiles are lightweight dictionaries consumed by Wrestler(profile=...).
# They can be expanded over time (archetype, moveset, stats, cosmetics, etc.).

ROSTER: dict[str, dict] = {
    # NOTE: Roster keys are slugs (stable IDs). Displayed names live in profile fields.
    "tre_legitimate": {
        "name": "Tre Legitimate",
        "short_name": "Tre",
        "archetype": "BALANCED",
        "weight_class": "Heavy",
        "style": "Balanced",
        "finisher": "grap_superplex",
        "ai_traits": {"GREED": 60, "GOOD": 20, "BAD": 10, "RND": 10},
        "bio": "A solid all-rounder. No excuses—just results.",
        "moveset": [
            # Neutral / safety
            "grap_lock_up",
            "util_taunt",
            "util_rest",
            "def_defensive",
            # Stand-up
            "strike_jab",
            "strike_front_kick",
            "strike_haymaker",
            "strike_spinning_backfist",
            "strike_desperation_slap",
            # Weak grapple ecosystem
            "util_deepen_hold",
            "grap_wrist_escape",
            "grap_fight_for_control",
            "grap_shove_off",
            "grap_headlock_takeover",
            "grap_arm_drag",
            "grap_irish_whip",
            "grap_snap_suplex",
            # Strong grapple ecosystem
            "grap_break_hold",
            "grap_ddt",
            "grap_belly_to_belly",
            # Running / positioning
            "util_charge",
            "util_stop_short",
            "util_regain_balance",
            "strike_rebound_lariat",
            "strike_sliding_dropkick",
            "strike_tree_shaker",
            "strike_clothesline",
            "grap_running_bulldog",
            # Grounded / recovery
            "util_ground_roll",
            "util_slow_stand_up",
            "util_kip_up",
            "strike_upkick",
            "strike_stomp",
            "util_pick_up",
            # Pins / subs
            "pin_pin",
            "sub_submission_hold",
            # Top rope
            "air_climb_turnbuckle",
            "air_climb_down",
            "grap_superplex",
        ],
    },
    "don_burner": {
        "name": "Don Burner, Head Turner",
        "short_name": "Don Burner",
        "archetype": "BALANCED",
        "weight_class": "Heavy",
        "style": "Brawler",
        "finisher": "grap_powerbomb",
        "ai_traits": {"GREED": 60, "GOOD": 20, "BAD": 10, "RND": 10},
        "bio": "A no-nonsense bruiser built to punish mistakes.",
        "moveset": [
            "grap_lock_up",
            "util_taunt",
            "util_rest",
            "def_defensive",
            # Stand-up strikes
            "strike_jab",
            "strike_front_kick",
            "strike_haymaker",
            "strike_spinning_backfist",
            "strike_desperation_slap",
            "strike_chop",
            # Weak grapple
            "util_deepen_hold",
            "grap_wrist_escape",
            "grap_fight_for_control",
            "grap_shove_off",
            "grap_headlock_takeover",
            "grap_snap_suplex",
            "grap_irish_whip",
            # Strong grapple power
            "grap_break_hold",
            "grap_powerbomb",
            "grap_belly_to_belly",
            "sub_bearhug",
            # Running brawl
            "util_charge",
            "strike_running_big_boot",
            "strike_running_clothesline",
            "strike_rebound_lariat",
            "util_stop_short",
            "util_regain_balance",
            # Grounded
            "util_ground_roll",
            "util_slow_stand_up",
            "util_kip_up",
            "strike_stomp",
            "strike_upkick",
            "util_pick_up",
            # Finish / control
            "pin_pin",
            "sub_submission_hold",
        ],
    },
    "ivan_mindset": {
        "name": "Ivan Mindset",
        "short_name": "Ivan",
        "archetype": "BALANCED",
        "weight_class": "Cruiser",
        "style": "Technician",
        "finisher": "sub_submission_hold",
        "ai_traits": {"GREED": 10, "GOOD": 70, "BAD": 10, "RND": 10},
        "bio": "Fast hands, faster brain. Will take an inch and turn it into a hold.",
        "moveset": [
            "grap_lock_up",
            "util_taunt",
            "util_rest",
            "def_defensive",
            # Stand-up
            "strike_jab",
            "strike_front_kick",
            "strike_chop",
            # Weak grapple: lots of resets and control
            "util_deepen_hold",
            "grap_wrist_escape",
            "grap_fight_for_control",
            "grap_shove_off",
            "grap_arm_drag",
            "grap_headlock_takeover",
            "grap_irish_whip",
            # Strong grapple: submissions
            "grap_break_hold",
            "sub_ankle_lock",
            "sub_sharpshooter",
            "sub_submission_hold",
            # Back game: quick pin + escape options
            "grap_go_behind",
            "pin_schoolboy_pin",
            "grap_back_elbow_escape",
            # Movement
            "util_charge",
            "grap_running_hurricanrana",
            "util_stop_short",
            "util_regain_balance",
            # Grounded
            "util_ground_roll",
            "util_slow_stand_up",
            "util_kip_up",
            "strike_upkick",
            "util_pick_up",
        ],
    },

    # New selectable wrestlers
    "brad_vantage": {
        "name": "Brad Vantage",
        "short_name": "Brad",
        "archetype": "BALANCED",
        "weight_class": "Heavy",
        "style": "Striker",
        "finisher": "strike_haymaker",
        "ai_traits": {"GREED": 45, "GOOD": 35, "BAD": 10, "RND": 10},
        "bio": "A crisp striker with a mean right hand. Loves to keep it simple and sharp.",
        "moveset": [
            "grap_lock_up",
            "util_taunt",
            "util_rest",
            "def_defensive",
            # Stand-up striking focus
            "strike_jab",
            "strike_chop",
            "strike_front_kick",
            "strike_haymaker",
            "strike_spinning_backfist",
            "strike_desperation_slap",
            # Weak grapple (minimal but functional)
            "grap_fight_for_control",
            "grap_wrist_escape",
            "grap_shove_off",
            "grap_irish_whip",
            "grap_headlock_takeover",
            "grap_arm_drag",
            # Running offense
            "util_charge",
            "strike_rebound_lariat",
            "strike_sliding_dropkick",
            "strike_tree_shaker",
            "strike_running_clothesline",
            "strike_running_shoulder_block",
            "strike_running_stomp",
            "util_stop_short",
            "util_regain_balance",
            # Grounded
            "util_ground_roll",
            "util_slow_stand_up",
            "util_kip_up",
            "strike_upkick",
            "strike_stomp",
            "util_pick_up",
            # Finish
            "pin_pin",
        ],
    },
    "floyd_conflict_jr": {
        "name": "Floyd Conflict Jr.",
        "short_name": "Floyd",
        "archetype": "BALANCED",
        "weight_class": "Heavy",
        "style": "Grappler",
        "finisher": "grap_belly_to_belly",
        "ai_traits": {"GREED": 55, "GOOD": 25, "BAD": 10, "RND": 10},
        "bio": "Second-generation scrapper who thrives in tight quarters and ugly grapples.",
        "moveset": [
            "grap_lock_up",
            "util_taunt",
            "util_rest",
            "def_defensive",
            # Stand-up
            "strike_jab",
            "strike_front_kick",
            "strike_chop",
            # Weak grapple: advance, throw, whip
            "util_deepen_hold",
            "grap_wrist_escape",
            "grap_fight_for_control",
            "grap_shove_off",
            "grap_headlock_takeover",
            "grap_snap_suplex",
            "grap_irish_whip",
            # Strong grapple: heavy work
            "grap_break_hold",
            "grap_belly_to_belly",
            "grap_piledriver",
            "sub_bearhug",
            # Back position: classic suplexes
            "grap_go_behind",
            "grap_back_suplex",
            "grap_backbreaker",
            "grap_back_elbow_escape",
            # Grounded
            "util_ground_roll",
            "util_slow_stand_up",
            "util_kip_up",
            "strike_stomp",
            "util_pick_up",
            # Finish / enders
            "pin_pin",
            "sub_submission_hold",
        ],
    },
    "super_delicious_brent": {
        "name": "Super-Delicious Brent",
        "short_name": "Brent",
        "archetype": "SUPERSTAR",
        "weight_class": "Cruiser",
        "style": "Showman",
        "finisher": "air_frog_splash",
        "ai_traits": {"GREED": 35, "GOOD": 45, "BAD": 10, "RND": 10},
        "bio": "All flash, all gas. The crowd loves him—and he knows it.",
        "moveset": [
            "grap_lock_up",
            "util_taunt",
            "util_rest",
            "def_defensive",
            # Stand-up
            "strike_jab",
            "strike_front_kick",
            "strike_chop",
            # Weak grapple: keep it light
            "grap_fight_for_control",
            "grap_wrist_escape",
            "grap_shove_off",
            "grap_irish_whip",
            "grap_arm_drag",
            # Running / rope game
            "util_charge",
            "strike_sliding_dropkick",
            "strike_rebound_lariat",
            "grap_running_hurricanrana",
            "grap_running_bulldog",
            "util_stop_short",
            "util_regain_balance",
            # Top rope ecosystem
            "air_climb_turnbuckle",
            "air_climb_down",
            "air_elbow_drop",
            "air_leg_drop",
            "air_diving_elbow",
            "air_moonsault",
            "air_frog_splash",
            "air_shooting_star_press",
            # Grounded
            "util_ground_roll",
            "util_slow_stand_up",
            "util_kip_up",
            "strike_upkick",
            "util_pick_up",
            # Finish / pins
            "pin_pin",
            "air_frog_splash",
        ],
    },
    "neon_casarrubias": {
        "name": "Neon Casarrubias",
        "short_name": "Neon",
        "archetype": "BALANCED",
        "weight_class": "Cruiser",
        "style": "Technician",
        "finisher": "sub_ankle_lock",
        "ai_traits": {"GREED": 20, "GOOD": 60, "BAD": 10, "RND": 10},
        "bio": "A slick tactician with a nasty streak for limbs. Precision over power.",
        "moveset": [
            "grap_lock_up",
            "util_taunt",
            "util_rest",
            "def_defensive",
            # Stand-up
            "strike_jab",
            "strike_front_kick",
            "strike_chop",
            # Weak grapple: control + resets
            "util_deepen_hold",
            "grap_wrist_escape",
            "grap_fight_for_control",
            "grap_shove_off",
            "grap_arm_drag",
            "grap_headlock_takeover",
            "grap_irish_whip",
            # Strong grapple: limb hunts
            "grap_break_hold",
            "sub_ankle_lock",
            "sub_submission_hold",
            # Back tools
            "grap_go_behind",
            "pin_schoolboy_pin",
            "grap_back_elbow_escape",
            # Grounded
            "util_ground_roll",
            "util_slow_stand_up",
            "util_kip_up",
            "strike_upkick",
            "util_pick_up",
        ],
    },
    "malice_anderson": {
        "name": "\"Malice\" Anderson",
        "short_name": "Malice",
        "archetype": "BALANCED",
        "weight_class": "Heavy",
        "style": "Brawler",
        "finisher": "strike_spinning_backfist",
        "ai_traits": {"GREED": 65, "GOOD": 15, "BAD": 10, "RND": 10},
        "bio": "A streetfight specialist who turns exchanges into disasters—especially for you.",
        "moveset": [
            "grap_lock_up",
            "util_taunt",
            "util_rest",
            "def_defensive",
            # Stand-up brawl
            "strike_jab",
            "strike_chop",
            "strike_front_kick",
            "strike_spinning_backfist",
            "strike_haymaker",
            "strike_desperation_slap",
            # Weak grapple (dirty defense)
            "grap_fight_for_control",
            "grap_wrist_escape",
            "grap_shove_off",
            "strike_desperation_punch",
            "strike_bite",
            "grap_irish_whip",
            "grap_snap_suplex",
            # Strong grapple
            "grap_break_hold",
            "grap_ddt",
            "grap_piledriver",
            # Running
            "util_charge",
            "strike_running_big_boot",
            "strike_running_clothesline",
            "strike_rebound_lariat",
            "util_stop_short",
            "util_regain_balance",
            # Grounded
            "util_ground_roll",
            "util_slow_stand_up",
            "util_kip_up",
            "strike_stomp",
            "strike_upkick",
            "util_pick_up",
            # End
            "pin_pin",
            "sub_submission_hold",
        ],
    },
    "fatal_mcguire": {
        "name": "Fatal McGuire",
        "short_name": "Fatal",
        "archetype": "SUPERSTAR",
        "weight_class": "Super Heavy",
        "style": "Giant",
        "finisher": "grap_powerbomb",
        "ai_traits": {"GREED": 70, "GOOD": 15, "BAD": 10, "RND": 5},
        "bio": "A crushing super heavyweight. If you're fresh, you're probably not lifting him.",
        "moveset": [
            "grap_lock_up",
            "util_taunt",
            "util_rest",
            "def_defensive",
            # Stand-up
            "strike_jab",
            "strike_chop",
            "strike_front_kick",
            "strike_haymaker",
            # Weak grapple
            "util_deepen_hold",
            "grap_wrist_escape",
            "grap_fight_for_control",
            "grap_shove_off",
            "grap_irish_whip",
            "grap_headlock_takeover",
            # Strong grapple power
            "grap_break_hold",
            "grap_powerbomb",
            "grap_belly_to_belly",
            "sub_bearhug",
            "grap_piledriver",
            # Back position
            "grap_go_behind",
            "grap_german_suplex",
            "grap_back_suplex",
            "grap_backbreaker",
            "grap_back_elbow_escape",
            "pin_schoolboy_pin",
            # Running
            "util_charge",
            "strike_running_big_boot",
            "strike_running_clothesline",
            "strike_rebound_lariat",
            "util_stop_short",
            "util_regain_balance",
            # Grounded
            "util_ground_roll",
            "util_slow_stand_up",
            "util_kip_up",
            "strike_stomp",
            "strike_upkick",
            "util_pick_up",
            # End
            "pin_pin",
            "sub_submission_hold",
        ],
    },
}

DEFAULT_PLAYER_PROFILE = "tre_legitimate"
DEFAULT_CPU_PROFILE = "don_burner"
